### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by kemelzaidan** [laserlemon/simple_oauth#19]
What kind of error is this:

```shell
/Library/Ruby/Gems/2.0.0/gems/simple_oauth-0.3.0/lib/simple_oauth/header.rb:88:in `attributes': SimpleOAuth: Found extra option keys not matching ATTRIBUTE_KEYS: (RuntimeError)
  [:consumer_secret, :token_secret]
	from /Library/Ruby/Gems/2.0.0/gems/simple_oauth-0.3.0/lib/simple_oauth/header.rb:74:in `signed_attributes'
	from /Library/Ruby/Gems/2.0.0/gems/simple_oauth-0.3.0/lib/simple_oauth/header.rb:80:in `normalized_attributes'
	from /Library/Ruby/Gems/2.0.0/gems/simple_oauth-0.3.0/lib/simple_oauth/header.rb:62:in `to_s'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:107:in `%'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:107:in `encode_field'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:117:in `encode_auth'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:127:in `block in encode_headers'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:122:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:122:in `inject'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_encoding.rb:122:in `encode_headers'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/client.rb:193:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/client.rb:61:in `connection_completed'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:97:in `block in finalize_request'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:151:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:151:in `set_deferred_status'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:191:in `succeed'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:165:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:159:in `connection_completed'
	from /Library/Ruby/Gems/2.0.0/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:27:in `connection_completed'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:403:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:143:in `userstream'
	from bot.rb:61:in `<main>'
```

Found this thread on stackoverflow too: http://stackoverflow.com/questions/26295611/ruby-simpleoauth-error and just can't find what is wrong

Just can't use the workaround on stackoverflow because there seems to be another library which uses simple_oauth 0.3 as a dependency and I want to avoid dependency hell.

**Comment by kemelzaidan** [comment]
So? How it's going to be solved? It makes the gem useless...

**Comment by laserlemon** [comment]
Is anybody willing to write a failing test, or even better… a failing test and the code to make it pass? :) @sferik, have you taken a look at this? @mpapis?

**Comment by mpapis** [comment]
it's fixed with https://github.com/laserlemon/simple_oauth/commit/e772b6734c0bda1080a3502b9fabdb15fd46b1c9 and released as https://github.com/laserlemon/simple_oauth/releases/tag/v0.3.1
